version: "3"
services:
    eventstore:
        image: "eventstore/eventstore"
        ports:
            - "2113:2113"
            - "1113:1113"
        environment:
            - EVENTSTORE_EXT_HTTP_PORT=2113
            - EVENTSTORE_EXT_TCP_PORT=1113
    ravendb:
        image: "ravendb/ravendb"
        ports:
            - "8080:8080"
        environment:
            - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
            - RAVEN_ARGS="--Setup.Mode=None"